version: '3.8'

services:
  agendasim-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JWT_SECRET=${JWT_SECRET}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./data:/app/data
    restart: unless-stopped
