services:
  - type: web
    name: agendasim-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JWT_SECRET
        generateValue: true
      - key: DB_PASSWORD
        generateValue: true
    healthCheckPath: /actuator/health
