services:
  - type: web
    name: agendasim-api
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JWT_SECRET
        generateValue: true
      - key: DB_PASSWORD
        generateValue: true
    healthCheckPath: /actuator/health
